name: Continuous Integration

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Lint
      run: |
        yarn lint
    - name: Test
      run: |
        yarn test